# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'ZarinPal', '~> 1.1.15'
    pod 'ZarinPal_MPG', '~> 1.1.15'

end
